version: "3.9"

services:
  backend:
    build: ./backend/.
    volumes:
      - ./backend/:/code/
    ports:
      - "8080:8080"
    
  frontend:
    build: ./frontend/.
    command: npm start
    volumes:
      - ./frontend/:/code/
    ports:
      - "3000:3000"
    depends_on:
      - backend